trigger:
- refs/tags/*
pr:
- master

jobs:
- job: Ember_Tests

  condition: eq(variables['Build.Reason'], 'PullRequest')

  pool:
    vmImage: 'vs2017-win2016'

  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '8.x'
      displayName: 'Install Node.js'

    - script: |
        npm install -g yarn ember-cli        
      displayName: 'Setup global tools'

    - script: |
        yarn install
      displayName: 'npm install'

    - script: |
        yarn run lint:hbs
      displayName: 'Run Handlebars Linter'

    - script: |
        yarn run lint:js
      displayName: 'Run Javascript Linter'

    - script: |
        yarn test -r xunit
      displayName: 'Run Ember Tests'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'jUnit'
        testResultsFiles: '*-tests.xml'

- job: Ember_Try

  condition: eq(variables['Build.Reason'], 'PullRequest')

  pool:
    vmImage: 'vs2017-win2016'

  strategy:
    maxParallel: 6
    matrix:
      LTS_2_16:
        EMBER_TRY_SCENARIO: ember-lts-2.16
      LTS_2_18:
        EMBER_TRY_SCENARIO: ember-lts-2.18
      LTS_3.4:
        EMBER_TRY_SCENARIO: ember-lts-3.4
      Release:
        EMBER_TRY_SCENARIO: ember-release
      Beta:
        EMBER_TRY_SCENARIO: ember-beta
      Canary:
        EMBER_TRY_SCENARIO: ember-canary

  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '8.x'
      displayName: 'Install Node.js'

    - script: |
        npm install -g yarn ember-cli
      displayName: 'Setup global tools'
      
    - script: |
        yarn install
      displayName: 'Install Dependencies'

    - script: |
        ember try:one $(EMBER_TRY_SCENARIO) --skip-cleanup=true
      displayName: 'Run Ember Try'

- job: Release_Deployment

  condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')

  pool:
    vmImage: 'vs2017-win2016'

  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '8.x'
      displayName: 'Install Node.js'

    - script: |
        npm install -g yarn ember-cli
      displayName: 'Setup global tools'
      
    - script: |
        yarn install
      displayName: 'Install Dependencies'

    - script: |
        npm publish
      displayName: 'Publish to NPM'

    - script: |
        ember deploy production
      displayName: 'Deploy Demo App to Github'

        


